version: '2.1'

services:
  timja-testing:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/platops/timja-testing
    ports:
      - $SERVER_PORT:$SERVER_PORT
